language: python

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

services:
  - mysql

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.

        # The following three variables are for tox. TOXENV is a standard
        # variable that tox uses to determine the environment to run,
        # TOXARGS are arguments passed to tox, and TOXPOSARGS are arguments
        # that tox passes through to the {posargs} indicator in tox.ini.
        # The latter can be used for example to pass arguments to pytest.
        - TOXENV='test'
        - TOXARGS='-v'
        - TOXPOSARGS=''
        - EVENT_TYPE='pull_request push'

jobs:
    # Don't wait for allowed failures
    fast_finish: true

    include:
        # Try MacOS X, usually enough only to run from cron as hardly there are
        # issues that are not picked up by a linux worker. We set language to
        # 'c' since 'python' doesn't work on non-Linux platforms.
        - os: osx
          language: c
          name: Python 3.7 with required dependencies
          env: PYTHON_VERSION=3.7 TOXENV=py37-test

        # Do a regular build on Linux with Python 3.7, with cov
        # For Linux we use language: python to avoid using conda.
        - os: linux
          python: "3.7"
          name: Python 3.7 with required dependencies and measure coverage
          env: TOXENV=py37-test-cov

        # Run test with Python 3.7 and developer dependencies of numpy, astropy
        - os: linux
          python: "3.7"
          name: Python 3.7 latest developer version of key dependencies
          env: TOXENV=py37-test-devdeps

        # Check for sphinx doc build warnings
        - os: linux
          python: "3.7"
          name: Documentation build
          env: TOXENV=build_docs

        # Do a code style check
        - os: linux
          python: "3.7"
          name: Code style checks
          env: TOXENV=codestyle

before_install:
    - pip uninstall -y numpy
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi

install:

    # We now use the ci-helpers package to set up our Python environment
    # on Windows and MacOS X but we don't set up any other dependencies,
    # instead using tox to do this. See https://github.com/astropy/ci-helpers
    # for more information about ci-helpers.

    - if [[ $TRAVIS_OS_NAME != linux ]]; then
        git clone --depth 1 git://github.com/astropy/ci-helpers.git;
        source ci-helpers/travis/setup_conda.sh;
      fi

script:
    - echo (which python)
    - pip install tox
    - tox $TOXARGS -- $TOXPOSARGS -m 'not e2e'

after_success:
    # If coveralls.io is set up for this package, uncomment the line below.
    # The coveragerc file may be customized as needed for your package.
    - if [[ "$SETUP_CMD" == '--coverage' ]]; then coveralls --rcfile='banzai/tests/coveragerc'; fi
