services:
  redis:
    image: redis:7
    container_name: banzai-redis
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: banzai-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  banzai-worker:
    build: .
    container_name: banzai-worker
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ${HOST_RAW_DIR}:/raw
      - ${HOST_REDUCED_DIR}:/reduced
    environment:
      - TASK_HOST=redis://redis:6379/0
      - FITS_BROKER=rabbitmq
      - FITS_EXCHANGE=fits_files
      - CELERY_TASK_QUEUE_NAME=reduction_task_queue
      - BANZAI_WORKER_LOGLEVEL=${BANZAI_WORKER_LOGLEVEL}
      - OMP_NUM_THREADS=${OMP_NUM_THREADS}
      - OPENTSDB_PYTHON_METRICS_TEST_MODE=${OPENTSDB_PYTHON_METRICS_TEST_MODE}
      - API_ROOT=${API_ROOT}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - DATA_ROOT=/reduced
    command: ["celery", "-A", "banzai.scheduling", "worker", "--hostname", "banzai-worker-local", "-l", "${BANZAI_WORKER_LOGLEVEL}", "-c", "4", "-Q", "reduction_task_queue"]
    restart: unless-stopped

  banzai-large-worker:
    build: .
    container_name: banzai-large-worker
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ${HOST_RAW_DIR}:/raw
      - ${HOST_REDUCED_DIR}:/reduced
    environment:
      - TASK_HOST=redis://redis:6379/0
      - FITS_BROKER=rabbitmq
      - FITS_EXCHANGE=fits_files
      - CELERY_LARGE_TASK_QUEUE_NAME=large_reduction_task_queue
      - BANZAI_WORKER_LOGLEVEL=${BANZAI_WORKER_LOGLEVEL}
      - OMP_NUM_THREADS=${OMP_NUM_THREADS}
      - OPENTSDB_PYTHON_METRICS_TEST_MODE=${OPENTSDB_PYTHON_METRICS_TEST_MODE}
      - API_ROOT=${API_ROOT}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - DATA_ROOT=/reduced
    command: ["celery", "-A", "banzai.scheduling", "worker", "--hostname", "banzai-large-worker-local", "-l", "${BANZAI_WORKER_LOGLEVEL}", "-c", "4", "-Q", "large_reduction_task_queue"]
    restart: unless-stopped

  banzai-listener:
    build: .
    container_name: banzai-listener
    depends_on:
      - redis
      - rabbitmq
      - banzai-worker
    volumes:
      - ${HOST_RAW_DIR}:/raw
      - ${HOST_REDUCED_DIR}:/reduced
    environment:
      - DB_ADDRESS=${DB_ADDRESS}
      - CAL_DB_ADDRESS=${CAL_DB_ADDRESS:-${DB_ADDRESS}}
      - API_ROOT=${API_ROOT}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - BANZAI_WORKER_LOGLEVEL=${BANZAI_WORKER_LOGLEVEL}
      - CELERY_LARGE_TASK_QUEUE_NAME=large_reduction_task_queue
      - CELERY_TASK_QUEUE_NAME=reduction_task_queue
      - TASK_HOST=redis://redis:6379/0
      - FITS_EXCHANGE=fits_files
      - OPENTSDB_PYTHON_METRICS_TEST_MODE=${OPENTSDB_PYTHON_METRICS_TEST_MODE}
    entrypoint: ["banzai_run_realtime_pipeline", "--fpack", "--no-bpm",
                 "--broker-url=amqp://rabbitmq:5672",
                 "--db-address=${DB_ADDRESS}",
                 "--calibration-db-address=${CAL_DB_ADDRESS}",
                 "--processed-path=/reduced"]
    restart: unless-stopped
