version: '0'
services:
  database:
    image: postgis/postgis
    container_name: banzai_database
    ports:
      - ${PGPORT}:5432
    user: 1024:100
    volumes:
      - /nfs/data/primefocus/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PGNAME}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
  astrometry:
    build: /home/primefocus/gaia-astrometry.net-service
    container_name: banzai_astrometry
    ports:
      - 5000:80
    volumes:
      - /nfs/data/primefocus/gaia-astrometry.net-indices:/index
    environment:
      MAX_REQUESTS: 5
      INDEX_FILE_PATH: /index
      GUNICORN_WORKERS: 3
      WORKER_TIMEOUT_SECONDS: 120
      GRACEFUL_TIMEOUT: 120
  photometry:
    build: /home/primefocus/photometric-catalog-service
    container_name: banzai_photometry
    ports:
      - 5005:80
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      CATALOG_DB_URL: postgresql://${PGUSER}:${PGPASSWORD}@host.docker.internal:${PGPORT}/${PGNAME}
