version: '2'
services:
  banzai-e2e:
    image: docker.lco.global/banzai-e2e-data:1.0.1
    container_name: banzai-e2e
    entrypoint:
    - /bin/true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
    volumes:
    - banzaie2e:/archive
    logging:
      options:
        max-size: '100m'
        max-file: '3'
  banzai-fits-exchange:
    image: rabbitmq:3.7.9
    container_name: banzai-fits-exchange
    mem_limit: '1g'
    logging:
      options:
        max-size: '100m'
        max-file: '3'
  banzai-redis:
    image: redis:5.0.3
    container_name: banzai-redis
    labels:
      io.rancher.container.pull_image: always
    mem_limit: '1g'
  banzai-init:
    image: ${DOCKER_IMG}
    container_name: banzai-init
    working_dir: /lco/banzai
    depends_on:
      - banzai-e2e
    entrypoint: ["python", "-c", "from banzai.tests import test_end_to_end;
                 test_end_to_end.init(); exit()"]
    environment:
      DB_ADDRESS: sqlite:////archive/engineering/test.db
    volumes_from:
      - banzai-e2e
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: banzai-e2e
    logging:
      options:
        max-size: '100m'
        max-file: '3'
  banzai-celery-workers:
    image: ${DOCKER_IMG}
    container_name: banzai-celery-workers
    entrypoint: ["celery", "-A", "banzai", "worker",
                 "--hostname", "banzai-celery-worker",
                 "-l", "debug"]
    mem_limit: '8g'
    depends_on:
      - banzai-redis
      - banzai-fits-exchange
      - banzai-e2e
      - banzai-init
    links:
      - banzai-redis:redis
    volumes_from:
      - banzai-e2e
    environment:
      RETRY_DELAY: "0"
      REDIS_HOST: "redis://redis:6379/0"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: banzai-e2e
    logging:
      options:
        max-size: '100m'
        max-file: '3'
  banzai-celery-beat:
    image: ${DOCKER_IMG}
    container_name: banzai-celery-beat
    entrypoint: ["celery", "-A", "banzai", "beat",
                 "-l", "debug"]
    mem_limit: '8g'
    depends_on:
      - banzai-redis
      - banzai-fits-exchange
      - banzai-e2e
      - banzai-init
    links:
      - banzai-redis:redis
    volumes_from:
      - banzai-e2e
    environment:
      RETRY_DELAY: "0"
      REDIS_HOST: "redis://redis:6379/0"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: banzai-e2e
    logging:
      options:
        max-size: '100m'
        max-file: '3'
  banzai-listener:
    image: ${DOCKER_IMG}
    container_name: banzai-listener
    mem_limit: '1g'
    depends_on:
      - banzai-redis
      - banzai-fits-exchange
      - banzai-e2e
      - banzai-init
    links:
      - banzai-fits-exchange:broker
      - banzai-redis:redis
    entrypoint: ["banzai_run_realtime_pipeline", "--fpack",
                 "--db-address=sqlite:////archive/engineering/test.db",
                 "--broker-url=broker"]
    environment:
      DB_ADDRESS: sqlite:////archive/engineering/test.db
      REDIS_HOST: "redis://redis:6379/0"
      FITS_BROKER_URL: "broker"
    volumes_from:
    - banzai-e2e
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: banzai-e2e
    logging:
      options:
        max-size: '100m'
        max-file: '3'
volumes:
  banzaie2e:
    driver: local
