version: '2'
services:
  BANZAIpipelineE2EData:
    image: docker.lco.global/banzai-e2e-data:1.0.1
    entrypoint:
    - /bin/true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
    volumes:
    - banzaie2e:/archive
    logging:
      options:
        max-size: '100m'
        max-file: '3'
  BANZAITest:
    image: ${DOCKER_IMG}
    entrypoint:
    - tail
    command: ["-f", "/dev/null"]
    environment:
      DB_ADDRESS: sqlite:////archive/engineering/test.db
    volumes_from:
    - BANZAIpipelineE2EData
    labels:
      io.rancher.container.pull_image: always
    logging:
      options:
        max-size: '100m'
        max-file: '3'
volumes:
  banzaie2e:
    driver: local
