# This environment was produced with the following: 
# conda create -n banzai python3.10 'cython<3' 'numpy<1.24' bottleneck scipy astropy pytest mock requests ipython coverage pyyaml kombu sep 'elasticsearch<6.0.0,>5.0.0' pytest-astropy mysql-connector-python photutils psycopg2-binary tenacity 'amqp<3' 'celery[redis]>
# python-dateutil 'sqlalchemy>1.3.0b1' psycopg2-binary apscheduler 'pytorch>1.6.0' --channel conda-forge --channel astropy --channel pytorch --solver
channels:
  - pytorch
  - conda-forge
  - astropy
  - defaults
dependencies:
  - affine=2.4.0
  - amqp=2.6.1
  - anyio=4.0.0
  - aom=3.6.1
  - apscheduler=3.10.4
  - asdf=2.15.1
  - asdf-astropy=0.4.0
  - asdf-coordinates-schemas=0.2.0
  - asdf-standard=1.0.3
  - asdf-transform-schemas=0.3.0
  - asdf-unit-schemas=0.1.0
  - asdf-wcs-schemas=0.1.1
  - astropy=5.3.4
  - asttokens=2.4.0
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache
  - backports.zoneinfo=0.2.1
  - billiard3.6.4.0
  - blosc1.21.5
  - bottleneck1.3.7
  - brotli1.1.0
  - brotli-bin1.1.0
  - brotli-python1.1.0
  - brunsli0.1
  - bzip21.0.8
  - c-ares1.20.1
  - c-blosc22.10.5
  - ca-certificates2023.7.22
  - cairo1.18.0
  - celery4.4.0
  - certifi2023.7.22
  - cffi1.16.0
  - cfitsio4.3.0
  - charls2.4.2
  - charset-normalizer3.3.0
  - click8.1.7
  - click-plugins1.1.1
  - cligj0.7.2
  - colorama0.4.6
  - contourpy1.1.1
  - coverage7.3.2
  - cryptography41.0.4
  - cycler0.12.1
  - cython0.29.36
  - dav1d1.2.1
  - decorator5.1.1
  - dnspython2.4.2
  - elasticsearch5.5.3
  - emcee3.1.4
  - exceptiongroup1.1.3
  - executing1.2.0
  - expat2.5.0
  - font-ttf-dejavu-sans-mono2.37
  - font-ttf-inconsolata3.000
  - font-ttf-source-code-pro2.038
  - font-ttf-ubuntu0.83
  - fontconfig2.14.2
  - fonts-conda-ecosystem1
  - fonts-conda-forge1
  - fonttools4.43.1
  - freetype2.12.1
  - freexl2.0.0
  - geos3.12.0
  - geotiff1.7.1
  - gettext0.21.1
  - giflib5.2.1
  - greenlet3.0.0
  - gwcs0.19.0
  - h110.14.0
  - h24.1.0
  - hdf44.2.15
  - hdf51.14.2
  - hpack4.0.0
  - httpcore1.0.0
  - hyperframe6.0.1
  - hypothesis6.87.4
  - icu73.2
  - idna3.4
  - imagecodecs2023.9.18
  - imageio2.31.5
  - importlib-metadata6.8.0
  - importlib-resources6.1.0
  - importlib_resources6.1.0
  - iniconfig2.0.0
  - intel-openmp2022.1.0
  - ipython8.16.1
  - jedi0.19.1
  - jmespath1.0.1
  - joblib1.3.2
  - json-c0.17
  - jsonschema4.19.1
  - jsonschema-specifications2023.7.1
  - jxrlib1.1
  - kealib1.5.2
  - keyutils1.6.1
  - kiwisolver1.4.5
  - krb51.21.2
  - lazy_loader0.3
  - lcms22.15
  - ld_impl_linux-642.40
  - lerc4.0.0
  - libaec1.1.2
  - libarchive3.7.2
  - libavif161.0.1
  - libblas3.9.0
  - libboost-headers1.82.0
  - libbrotlicommon1.1.0
  - libbrotlidec1.1.0
  - libbrotlienc1.1.0
  - libcblas3.9.0
  - libcurl8.4.0
  - libdeflate1.19
  - libedit3.1.20191231
  - libev4.33
  - libexpat2.5.0
  - libffi3.4.2
  - libgcc-ng13.2.0
  - libgdal3.7.2
  - libgfortran-ng13.2.0
  - libgfortran513.2.0
  - libglib2.78.0
  - libgomp13.2.0
  - libiconv1.17
  - libjpeg-turbo3.0.0
  - libkml1.3.0
  - liblapack3.9.0
  - libnetcdf4.9.2
  - libnghttp21.52.0
  - libnsl2.0.0
  - libopenblas0.3.24
  - libpng1.6.39
  - libpq16.0
  - libprotobuf3.20.3
  - librttopo1.1.0
  - libspatialite5.1.0
  - libsqlite3.43.2
  - libssh21.11.0
  - libstdcxx-ng13.2.0
  - libtiff4.6.0
  - libuuid2.38.1
  - libwebp-base1.3.2
  - libxcb1.15
  - libxml22.11.5
  - libzip1.10.1
  - libzlib1.2.13
  - libzopfli1.0.3
  - lz4-c1.9.4
  - lzo2.10
  - matplotlib-base3.8.0
  - matplotlib-inline0.1.6
  - minizip4.0.1
  - mkl2022.1.0
  - mock5.1.0
  - munkres1.1.4
  - mysql-common8.0.33
  - mysql-connector-python8.0.32
  - mysql-libs8.0.33
  - ncurses6.4
  - networkx3.1
  - ninja1.11.1
  - nspr4.35
  - nss3.94
  - numpy1.23.5
  - openjpeg2.5.0
  - openssl3.1.3
  - packaging23.2
  - parso0.8.3
  - pcre210.40
  - pexpect4.8.0
  - photutils1.9.0
  - pickleshare0.7.5
  - pillow10.0.1
  - pip23.2.1
  - pixman0.42.2
  - pkgutil-resolve-name1.3.10
  - pluggy1.3.0
  - poppler23.10.0
  - poppler-data0.4.12
  - postgresql16.0
  - proj9.3.0
  - prompt-toolkit3.0.39
  - prompt_toolkit3.0.39
  - protobuf3.20.3
  - psutil5.9.5
  - psycopg22.9.7
  - psycopg2-binary2.9.7
  - pthread-stubs0.4
  - ptyprocess0.7.0
  - pure_eval0.2.2
  - pycparser2.21
  - pyerfa2.0.0.3
  - pygments2.16.1
  - pyparsing3.1.1
  - pysocks1.7.1
  - pytest7.4.2
  - pytest-arraydiff0.5.0
  - pytest-astropy0.10.0
  - pytest-astropy-header0.2.2
  - pytest-cov4.1.0
  - pytest-doctestplus1.0.0
  - pytest-filter-subpackage
  - pytest-mock
  - pytest-openfiles
  - pytest-remotedata
  - python=3.10.12
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.12.1
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - rasterio=1.3.8
  - rav1e=0.6.6
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rpds-py=0.10.6
  - scikit-image=0.22.0
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - semantic_version=2.10.0
  - sep=1.2.1
  - setuptools=68.2.2
  - shapely=2.0.2
  - simplejson=3.19.2
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sniffio=1.3.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sqlalchemy=2.0.22
  - sqlite=3.43.2
  - stack_data=0.6.2
  - svt-av1=1.7.0
  - tenacity=8.2.3
  - threadpoolctl=3.2.0
  - tifffile=2023.9.26
  - tiledb=2.16.3
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tqdm=4.66.1
  - traitlets=5.11.2
  - typing-extensions=4.8.0
  - tzcode=2023c
  - tzdata=2023c
  - tzlocal=5.1
  - unicodedata2=15.1.0
  - uriparser=0.9.7
  - wcwidth=0.2.8
  - wheel=0.41.2
  - xerces-c=3.2.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz=5.2.6
  - yaml=0.2.5
  - zfp=1.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.5
  - pip:
      - asciitree
      - astropy-healpix
      - async-timeout
      - boto3
      - botocore
      - cloudpickle
      - cosmic-conn
      - dask
      - fasteners
      - fsspec
      - kombu
      - lcogt-logging
      - locket
      - logutils
      - numcodecs
      - ocs-archive
      - ocs-ingester
      - opensearch-py
      - opentsdb-http-client
      - opentsdb-python-metrics
      - partd
      - pretty-errors
      - redis
      - reproject
      - s3transfer
      - toolz
      - urllib3
      - vine
      - zarr
