# This environment was produced with the following: 
# conda create -n banzai python=3.10 'cython<3' 'numpy<1.24' bottleneck scipy astropy pytest mock requests ipython coverage pyyaml kombu sep 'elasticsearch<6.0.0,>=5.0.0' pytest-astropy mysql-connector-python photutils psycopg2-binary tenacity 'amqp<3' 'celery[redis]>=4.3.1,<5' scikit-image emcee 
# python-dateutil 'sqlalchemy>=1.3.0b1' psycopg2-binary apscheduler 'pytorch>=1.6.0' --channel conda-forge --channel astropy --channel pytorch --solver=libmamba
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - aiobotocore=2.19.0
  - aiohappyeyeballs=2.4.6
  - aiohttp=3.11.12
  - aioitertools=0.12.0
  - aiosignal=1.3.2
  - alembic=1.14.1
  - amqp=5.2.0
  - aom=3.9.1
  - apscheduler=3.11.0
  - asdf=4.1.0
  - asdf-astropy=0.7.0
  - asdf-coordinates-schemas=0.3.0
  - asdf-standard=1.1.1
  - asdf-transform-schemas=0.5.0
  - asdf-wcs-schemas=0.4.0
  - astropy-iers-data=0.2025.2.10.0.33.26
  - asttokens=3.0.0
  - attrs=25.1.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - backports.zoneinfo=0.2.1
  - beautifulsoup4=4.13.3
  - billiard=4.2.1
  - bleach=6.2.0
  - blosc=1.21.6
  - boto3=1.36.3
  - botocore=1.36.3
  - bottleneck=1.4.2
  - bqplot=0.12.43
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.15.2
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - celery=5.4.0
  - certifi=2025.1.31
  - charls=2.4.2
  - charset-normalizer=3.4.1
  - click=8.1.8
  - click-didyoumean=0.3.1
  - click-plugins=1.1.1
  - click-repl=0.3.0
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - cython=3.0.12
  - dask-core=2025.1.0
  - dav1d=1.2.1
  - debugpy=1.8.12
  - decorator=5.1.1
  - emcee=3.1.6
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - filelock=3.17.0
  - fonttools=4.56.0
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.5.0
  - fsspec=2025.2.0
  - gast=0.4.0
  - geos=3.13.0
  - geotiff=1.7.3
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - greenlet=3.1.1
  - h5py=3.12.1
  - hdf5=1.14.4
  - html5lib=1.1
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.12.30
  - imageio=2.37.0
  - importlib-metadata=8.6.1
  - iniconfig=2.0.0
  - ipydatagrid=1.4.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.5
  - jmespath=1.0.1
  - jplephem=2.21
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - kombu=5.4.1
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.7
  - libarrow=19.0.0
  - libarrow-acero=19.0.0
  - libarrow-dataset=19.0.0
  - libarrow-substrait=19.0.0
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.11.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgdal-core=3.10.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.34.0
  - libgoogle-cloud-storage=2.34.0
  - libgrpc=1.67.1
  - libheif=1.19.5
  - libhwloc=2.11.2
  - libhwy=1.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libparquet=19.0.0
  - libpng=1.6.46
  - libpq=17.2
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=19.1.7
  - locket=1.0.0
  - logutils=0.3.5
  - lz4-c=1.10.0
  - lzo=2.10
  - mako=1.3.9
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - minizip=4.0.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - openjpeg=2.5.3
  - openldap=2.6.9
  - opensearch-py=2.5.0
  - openssl=3.4.1
  - orc=2.0.3
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - partd=1.4.2
  - pcre2=10.44
  - pexpect=4.9.0
  - photutils=2.1.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - proj=9.5.1
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - propcache=0.2.1
  - psutil=6.1.1
  - psycopg2=2.9.9
  - psycopg2-binary=2.9.9
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py2vega=0.6.1
  - pyarrow=19.0.0
  - pyarrow-core=19.0.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pyerfa=2.0.1.5
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.12
  - pytorch=2.5.1
  - pytz=2024.1
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - rasterio=1.4.3
  - rav1e=0.6.6
  - re2=2024.07.02
  - readline=8.2
  - regions=0.10
  - requests=2.32.3
  - s2n=1.5.11
  - s3fs=2025.2.0
  - s3transfer=0.11.2
  - scikit-image=0.25.1
  - scipy=1.15.1
  - semantic_version=2.10.0
  - setuptools=75.8.0
  - shapely=2.0.7
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlalchemy=2.0.38
  - sqlite=3.32.3
  - stack_data=0.6.3
  - svt-av1=2.3.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tenacity=9.0.0
  - tifffile=2025.1.10
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - tzlocal=5.2
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - urllib3=1.26.19
  - vine=5.1.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.2
  - x265=3.5
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zstd=1.5.6
  - pip:
      - astropy==5.3.4
      - astropy-healpix==1.1.0
      - cosmic-conn==0.4.1
      - crc32c==2.7.1
      - deprecated==1.2.18
      - donfig==0.8.1.post1
      - gwcs==0.21.0
      - lcogt-logging==0.3.2
      - numcodecs==0.15.1
      - numpy==1.26.4
      - ocs-archive==0.4.0
      - ocs-ingester==3.1.0
      - opentsdb-http-client==0.2.0
      - opentsdb-python-metrics==0.2.0
      - pretty-errors==1.2.25
      - redis==5.2.1
      - reproject==0.14.1
      - sep==1.4.0
      - zarr==3.0.2
