# This environment was produced with the following: 
# conda create -n banzai python=3.10 'cython<3' 'numpy<1.24' bottleneck scipy astropy pytest mock requests ipython coverage pyyaml kombu sep 'elasticsearch<6.0.0,>=5.0.0' pytest-astropy mysql-connector-python photutils psycopg2-binary tenacity 'amqp<3' 'celery[redis]>=4.3.1,<5' scikit-image emcee 
# python-dateutil 'sqlalchemy>=1.3.0b1' psycopg2-binary apscheduler 'pytorch>=1.6.0' --channel conda-forge --channel astropy --channel pytorch --solver=libmamba
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - affine=2.4.0
  - aiohappyeyeballs=2.4.6
  - aiohttp=3.11.12
  - aioitertools=0.12.0
  - aiosignal=1.3.2
  - amqp=5.2.0
  - aom=3.9.1
  - asdf=4.1.0
  - asdf-astropy=0.7.0
  - asdf-standard=1.1.1
  - astropy-iers-data=0.2025.2.10.0.33.26
  - asttokens=3.0.0
  - attrs=25.1.0
  - beautifulsoup4=4.13.3
  - billiard=4.2.1
  - boto3=1.36.3
  - bqplot=0.12.43
  - brunsli=0.1
  - dav1d=1.2.1
  - debugpy=1.8.12
  - fonttools=4.56.0
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.5.0
  - gast=0.4.0
  - geos=3.13.0
  - geotiff=1.7.3
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - greenlet=3.1.1
  - h5py=3.12.1
  - hdf5=1.14.4
  - html5lib=1.1
  - imageio=2.37.0
  - importlib-metadata=8.6.1
  - ipydatagrid=1.4.0
  - ipykernel=6.29.5
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.5
  - jmespath=1.0.1
  - jplephem=2.21
  - jupyterlab_widgets=3.0.13
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - kombu=5.4.1
  - lazy-loader=0.4
  - lazy_loader=0.4
  - libabseil=20240722.0
  - libarrow=19.0.0
  - libarrow-dataset=19.0.0
  - libarrow-substrait=19.0.0
  - libavif16=1.1.1
  - libblas=3.9.0
  - libde265=1.0.15
  - libdeflate=1.23
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libheif=1.19.5
  - libhwy=1.1.0
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblzma=5.6.4
  - libnsl=2.0.1
  - libparquet=19.0.0
  - libpng=1.6.46
  - libpq=17.2
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libzopfli=1.0.3
  - llvm-openmp=19.1.7
  - logutils=0.3.5
  - lzo=2.10
  - mako=1.3.9
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - minizip=4.0.7
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - networkx=3.4.2
  - openjpeg=2.5.3
  - openldap=2.6.9
  - pandas=2.2.3
  - parso=0.8.4
  - partd=1.4.2
  - photutils=2.1.0
  - pillow=11.1.0
  - proj=9.5.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - psutil=6.1.1
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - py2vega=0.6.1
  - pyarrow=19.0.0
  - pyerfa=2.0.1.5
  - pyparsing=3.2.1
  - pytest=8.3.4
  - pytz=2024.1
  - pywavelets=1.8.0
  - pyzmq=26.2.1
  - qhull=2020.2
  - rasterio=1.4.3
  - rav1e=0.6.6
  - re2=2024.07.02
  - regions=0.10
  - s2n=1.5.11
  - s3fs=2025.2.0
  - s3transfer=0.11.2
  - shapely=2.0.7
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - snuggs=1.4.7
  - soupsieve=2.5
  - svt-av1=2.3.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tifffile=2025.1.10
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - traittypes=0.2.1
  - uriparser=0.9.8
  - vine=5.1.0
  - widgetsnbextension=4.0.13
  - wrapt=1.17.2
  - x265=3.5
  - xorg-libxau=1.0.12
  - yarl=1.18.3
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.21.0
  - pip:
      - astropy==5.3.4
      - astropy-healpix==1.1.0
      - cosmic-conn==0.4.1
      - crc32c==2.7.1
      - deprecated==1.2.18
      - donfig==0.8.1.post1
      - gwcs==0.21.0
      - lcogt-logging==0.3.2
      - numcodecs==0.15.1
      - numpy==1.26.4
      - ocs-archive==0.4.0
      - ocs-ingester==3.1.0
      - opentsdb-http-client==0.2.0
      - opentsdb-python-metrics==0.2.0
      - pretty-errors==1.2.25
      - redis==5.2.1
      - reproject==0.14.1
      - sep==1.4.0
      - zarr==3.0.2
