# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /example
  # Name will be used as the value for the `app.kubernetes.io/component`
  # selector label and updated automatically by `kpt fn render`.
  # So no need to set those manually.
  name: workers
  labels:
    app.kubernetes.io/component: workers
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|example'
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: workers
  template:
    metadata:
      labels:
        app.kubernetes.io/component: workers
    spec:
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 20Gi
      containers:
        - name: default
          image: "banzai"
          command:
            - "celery"
            - "-A"
            - "banzai"
            - "worker"
            - "--without-heartbeat"
            - "--without-gossip"
            - "--without-mingle"
            - "--task-events"
            - "--concurrency"
            - "1"
            - "-l"
            - "info"
            - "-Q"
            - "$(CELERY_TASK_QUEUE_NAME)"
          env:
            - name: OMP_NUM_THREADS
              value: "2"
          envFrom:
            - configMapRef:
                name: env
                optional: false
            - secretRef:
                name: db-env
                optional: true
            - secretRef:
                name: rabbitmq-env
                optional: true
            - secretRef:
                name: archive-api-env
                optional: true
            - secretRef:
                name: env
                optional: true
