dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://charts.helm.sh/stable
  condition: useDockerizedDatabase

- name: rabbitmq
  version: 6.18.2
  repository: https://charts.helm.sh/stable
  condition: useDockerizedRabbitMQ
