dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: useDockerizedDatabase

- name: rabbitmq
  version: 6.18.2
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: useDockerizedRabbitMQ
