apiVersion: kpt.dev/v1
kind: RenderHelmChart
metadata: # kpt-merge: /example
  name: rabbitmq
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: kpt.dev|RenderHelmChart|default|example
# See https://catalog.kpt.dev/render-helm-chart/v0.2/
helmCharts:
  - chartArgs:
      repo: oci://registry-1.docker.io/bitnamicharts
      name: rabbitmq
      version: 16.0.10
    templateOptions:
      apiVersions:
        - 1.26.15
      releaseName: rabbitmq
      namespace: banzai-deps
      includeCRDs: true
      skipTests: true
      values:
        valuesInline:
          persistence:
            size: 512Mi
          auth:
            username: rabbitmq
            password: rabbitmq
