{{- if .Values.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ include "banzai.fullname" . -}} -worker
  labels:
{{ include "banzai.labels" . | indent 4 }}
spec:
  successfulJobsHistoryLimit: 30
  failedJobsHistoryLimit: 30
{{- with .Values.keda }}
  minReplicaCount: {{ .minReplicas }}
  maxReplicaCount: {{ .maxReplicas }}
{{- end }}
  rollout:
    strategy: gradual
    propagationPolicy: foreground
  scalingStrategy:
    strategy: default
  triggers:
    - type: rabbitmq
      metadata:
        hostFromEnv: TASK_HOST
        mode: QueueLength
        value: "1"
        activationValue: "1"
        queueName: {{ .Values.banzai.celeryTaskQueueName | quote }}
  jobTargetRef:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 600 # job will be killed after 10 mins
    backoffLimit: 0 # no retries
    template:
      metadata:
        labels:
          app.kubernetes.io/name: {{ include "banzai.name" . }}
          app.kubernetes.io/instance: "{{ .Release.Name }}"
          app.kubernetes.io/component: worker
      spec:
      {{- with .Values.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 10 }}
      {{- end }}
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 10 }}

        containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            command:
              - celery
              - -A
              - banzai
              - worker
              - --concurrency=1
              - --max-tasks-per-child=1
              - --pool=solo
              - --prefetch-multiplier=1
              - -l
              - info
              - -Q
              - $(CELERY_TASK_QUEUE_NAME)
            env:
              - name: CELERY_ACKS_LATE
                value: "True"
              - name: OMP_NUM_THREADS
                value: "2"
            {{- include "banzai.Env" . | nindent 14 }}
            volumeMounts:
              - mountPath: /tmp
                name: tmp
        restartPolicy: Never
        terminationGracePeriodSeconds: 120
        volumes:
          - name: tmp
            ephemeral:
              volumeClaimTemplate:
                metadata:
                  labeles:
                    app.kubernetes.io/name: {{ include "banzai.name" . }}
                    app.kubernetes.io/instance: "{{ .Release.Name }}"
                    app.kubernetes.io/component: worker
                spec:
                  accessModes:
                    - "ReadWriteOnce"
                  resources:
                    requests:
                      storage: 20Gi
      {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
      {{- end }}
{{- end }}
