{{- if .Values.horizontalPodAutoscaler.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "banzai.fullname" . -}} -large-workers
  labels:
{{ include "banzai.labels" . | indent 4 }}
spec:
{{- with .Values.horizontalPodAutoscaler }}
  minReplicas: {{ .minLargeReplicas }}
  maxReplicas: {{ .maxLargeReplicas }}
  targetCPUUtilizationPercentage: {{ .targetCPUUtilizationPercentage }}
{{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "banzai.fullname" . -}} -large-workers
{{- end }}
