apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "banzai.fullname" . -}} -workers
  labels:
{{ include "banzai.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "banzai.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "banzai.name" . }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: worker
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - "celery"
            - "-A"
            - "banzai"
            - "worker"
            - "--without-heartbeat"
            - "--without-gossip"
            - "--without-mingle"
            - "--task-events"
            - "--concurrency"
            - "1"
            - "-l"
            - "info"
            - "-Q"
            - "$(CELERY_TASK_QUEUE_NAME)"
          env:
            - name: OMP_NUM_THREADS
              value: "2"
            {{- include "banzai.Env" . | nindent 12 }}
          resources:
            requests:
              cpu: "0.5"
              memory: "4Gi"
              ephemeral-storage: "20Gi"
            limits:
              cpu: "2"
              memory: "8Gi"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: false
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 20Gi
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
