name: Code Style

on:
  pull_request:
    branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.12'
          enable-cache: true
      - name: Set up project
        run: uv sync --extra cpu --extra style
      - name: Code Style
        run: uv run pycodestyle --count --max-line-length=120
