name: Coverage

on:
  pull_request:
    branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.12'
          enable-cache: true
      - name: Set up project
        run: uv sync --locked --extra test
      - name: Run coverage
        run: uv run pytest --pyargs banzai.tests -m "not e2e" --cov banzai --cov-config="setup.cfg"
