name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Or macos-latest if needed

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Specify your desired version
      - name: Install dependencies
        run: pip install poetry
      - name: Set up project
        run: poetry install -E cpu -E docs
      - name: Build Docs
        run: poetry run sphinx-build -W -b html docs docs/_build/html
            