name: E2E Tests

on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    runs-on:
      - banzai-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.22.17"
        
      - name: Start a Kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Test
        run: |
          kubectl cluster-info
