name: E2E Tests

on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    runs-on:
      - banzai-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            accept-flake-config = true

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: lco-public
          extraPullNames: devenv
          skipPush: true

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Kind cluster
        shell: nix develop --impure --command bash -e {0}
        run: |
          kind-create-cluster

      - name: Deploy Banzai w/ Skaffold
        env:
          SKAFFOLD_BUILDX_ARGS: "--cache-to type=gha,mode=max,ignore-error=true --cache-from type=gha"
        shell: nix develop --impure --command bash -e {0}
        run: |
          skaffold -p e2e run

      - name: Test Master Bias Creation
        shell: nix develop --impure --command bash -e {0}
        run: |
          kubectl exec banzai-e2e-test -c banzai-listener -- pytest -s --pyargs banzai.tests --durations=0 --junitxml=/archive/engineering/pytest-master-bias.xml -m master_bias
