name: E2E Tests

on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    runs-on:
      - banzai-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.22.17"
        
      - name: Start a Kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          version: "v0.19.0"
          node_image: kindest/node:v1.22.17@sha256:9af784f45a584f6b28bce2af84c494d947a05bd709151466489008f80a9ce9d5
          wait: "600s"

      - name: Test
        run: |
          kubectl cluster-info
