apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata: # kpt-merge: /cronjob
  name: cronjob
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'kustomize.config.k8s.io|Kustomization|default|cronjob'
components:
  - ./remove-kpt-internal-annotations/
resources:
  - ./cronjob.yaml
